version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-test
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=solarwinds-swis-react-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/solarwinds-swis-react-datasource
    restart: unless-stopped